language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.1
matrix:
  exclude:
    - rvm: 2.3.1
      os: osx
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/907e95dada362be2a13c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
